version: '3.8'

services:
  updater:
    build: ./service_updater
    command: bash -c 'python tasks.py'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
    restart: always
    volumes:
      - C:\\МДГТ - (Учет рабоч. времени, Отпуск, Даты рожд., телефоны, план работ):/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  service_customers:
    build: ./service_customers/
    container_name: service_customers
    ports:
      - 9000:9000
    volumes:
      - /home/user_bot/databases/:/databases
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    service_control:
      build: ./service_control/
      container_name: service_control
      ports:
        - 8500:8500
      volumes:
        - /home/user_bot/disk-z:/files
        - /home/user_bot/databases/:/databases
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro

